// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCq3AQoPRVBhY2tldFByb3RvY29sEhkK",
            "FVBBQ0tFVF9QUk9UT0NPTF9TVEFSVBAAEhIKDkNTX0NoYXRSZXF1ZXN0EAES",
            "EwoPU0NfQ2hhdFJlc3BvbnNlEAISIQodQ1NfQ2lyY3VsYXJTZWN0b3JTa2ls",
            "bFJlcXVlc3QQAxIiCh5TQ19DaXJjdWxhclNlY3RvclNraWxsUmVzcG9uc2UQ",
            "BBIZChNQQUNLRVRfUFJPVE9DT0xfRU5EEP//AypRCgtFREJQcm90b2NvbBIV",
            "ChFEQl9QUk9UT0NPTF9TVEFSVBAAEhQKEFNHREJfU2VydmVyU3RhcnQQARIV",
            "Cg9EQl9QUk9UT0NPTF9FTkQQ//8DYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.EPacketProtocol), typeof(global::Protocol.EDBProtocol), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EPacketProtocol {
    [pbr::OriginalName("PACKET_PROTOCOL_START")] PacketProtocolStart = 0,
    [pbr::OriginalName("CS_ChatRequest")] CsChatRequest = 1,
    [pbr::OriginalName("SC_ChatResponse")] ScChatResponse = 2,
    [pbr::OriginalName("CS_CircularSectorSkillRequest")] CsCircularSectorSkillRequest = 3,
    [pbr::OriginalName("SC_CircularSectorSkillResponse")] ScCircularSectorSkillResponse = 4,
    [pbr::OriginalName("PACKET_PROTOCOL_END")] PacketProtocolEnd = 65535,
  }

  public enum EDBProtocol {
    [pbr::OriginalName("DB_PROTOCOL_START")] DbProtocolStart = 0,
    [pbr::OriginalName("SGDB_ServerStart")] SgdbServerStart = 1,
    [pbr::OriginalName("DB_PROTOCOL_END")] DbProtocolEnd = 65535,
  }

  #endregion

}

#endregion Designer generated code
